# Generated by Django 5.0.6 on 2024-05-13 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Cuser',
        ),
    ]
