# Generated by Django 5.0.6 on 2024-05-13 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_user_cuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='password',
        ),
        migrations.AddField(
            model_name='cuser',
            name='fname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuser',
            name='lname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
