# Generated by Django 5.0.6 on 2024-05-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0004_remove_comment_card_remove_review_card_comment_deck_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Deck',
            new_name='deck',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='Deck',
            new_name='deck',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='nicname',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
